spring:
  application:
    name: config-service-pfe
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DalalYouness/config-repo-pfe.git
    discovery:
      enabled: true
server:
  port: 8888


