#service  name
spring:
  application:
    name: config-service-pfe

#repository git url when we added our configurations
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DalalYouness/config-repo-pfe.git
    discovery:
      enabled: true

#vault url when we added our secrets
    vault:
      host: localhost
      scheme: http
      authentication: token
      token: ${VAULT_TOKEN}
      port: 8200

#server port
server:
  port: 8888
