spring:
  application:
    name: config-service-pfe
  main:
    allow-bean-definition-overriding: true

  profiles:
    active: git, vault

  cloud:
    config:
      server:
        git:
          uri: https://github.com/DalalYouness/config-repo-pfe.git

        vault:
          host: localhost
          port: 8200
          scheme: http
          kv-version: 2
          token: ${VAULT_TOKEN}
server:
  port: 8888
